src/Web/Controllers/CatalogController.cs
using Microsoft.eShopWeb.Web.Services;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace Microsoft.eShopWeb.Web.Controllers
{
    [Route("")]
    public class CatalogController : Controller
    {
        private readonly ICatalogService _catalogService;

        public CatalogController(ICatalogService catalogService) => _catalogService = catalogService;

        [HttpGet]
        [HttpPost]
        public async Task<IActionResult> Index(int? brandFilterApplied, int? typesFilterApplied, int? page)
        {
            var itemsPage = 10;           
            var catalogModel = await _catalogService.GetCatalogItems(page ?? 0, itemsPage, brandFilterApplied, typesFilterApplied);
            return View(catalogModel);
        }

        [HttpGet("Error")]
        public IActionResult Error()
        {
            return View();
        }
    }
}

src/Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"] - Microsoft.eShopOnWeb</title>

	<environment names="Development">
		<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
		<link rel="stylesheet" href="~/css/app.css" />
	</environment>
	<environment names="Staging,Production">
		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0-alpha.5/css/bootstrap.min.css"
			  asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
			  asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
		<link rel="stylesheet" href="~/css/app.min.css" asp-append-version="true" />
	</environment>
    <link rel="stylesheet" href="~/css/app.component.css" />
    <link rel="stylesheet" href="~/css/basket/basket.component.css" />
    <link rel="stylesheet" href="~/css/catalog/pager.css" />
  	<link rel="stylesheet" href="~/css/catalog/catalog.component.css" />
    <link rel="stylesheet" href="~/css/basket/basket-status/basket-status.component.css" />
    <link rel="stylesheet" href="~/css/orders/orders.component.css" />
</head>
<body>
	<header class="navbar navbar-light navbar-static-top">
		<div class="container">
			<article class="row">

				<section class="col-lg-7 col-md-6 col-xs-12">
					<a asp-area="" asp-controller="Catalog" asp-action="Index" class="navbar-brand">
						<img src="../images/brand.png" alt="eShop On Web"/>
					</a>
				</section>
                <partial name="_LoginPartial" />
			</article>
		</div>
	</header>

	@RenderBody()


	<footer class="esh-app-footer">
		<div class="container">
			<article class="row">

				<section class="col-sm-6">
				</section>

				<section class="col-sm-6">
					<div class="esh-app-footer-text hidden-xs"> e-ShopOnWeb. All rights reserved </div>
				</section>

			</article>
		</div>
	</footer>

	<environment names="Development">
		<script src="~/lib/jquery/dist/jquery.js"></script>
		<script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
		<script src="~/js/site.js" asp-append-version="true"></script>
	</environment>
	<environment names="Staging,Production">
		<script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
				asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
				asp-fallback-test="window.jQuery">
		</script>
		<script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/bootstrap.min.js"
				asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
				asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
		</script>
		<script src="~/js/site.min.js" asp-append-version="true"></script>
	</environment>

	@RenderSection("scripts", required: false)
</body>
</html>