src/Web/Controllers/Api/CatalogController.cs
using Microsoft.eShopWeb.Web.Services;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace Microsoft.eShopWeb.Web.Controllers.Api
{
    public class CatalogController : BaseApiController
    {
        private readonly ICatalogService _catalogService;

        public CatalogController(ICatalogService catalogService) => _catalogService = catalogService;

        [HttpGet]
        public async Task<IActionResult> List(int? brandFilterApplied, int? typesFilterApplied, int? page)
        {
            var itemsPage = 10;           
            var catalogModel = await _catalogService.GetCatalogItems(page ?? 0, itemsPage, brandFilterApplied, typesFilterApplied);
            return Ok(catalogModel);
        }
    }
}

src/Web/Controllers/BasketController.cs
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using Microsoft.eShopWeb.ApplicationCore.Interfaces;
using Microsoft.AspNetCore.Http;
using Microsoft.eShopWeb.Web.ViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.eShopWeb.Infrastructure.Identity;
using System;
using System.Collections.Generic;
using Microsoft.eShopWeb.ApplicationCore.Entities.OrderAggregate;
using Microsoft.AspNetCore.Authorization;
using Microsoft.eShopWeb.Web.Interfaces;

namespace Microsoft.eShopWeb.Web.Controllers
{
    [Route("[controller]/[action]")]
    public class BasketController : Controller
    {
        private readonly IBasketService _basketService;
        private readonly IUriComposer _uriComposer;
        private readonly SignInManager<ApplicationUser> _signInManager;
        private readonly IAppLogger<BasketController> _logger;
        private readonly IOrderService _orderService;
        private readonly IBasketViewModelService _basketViewModelService;

        public BasketController(IBasketService basketService,
            IBasketViewModelService basketViewModelService,
            IOrderService orderService,
            IUriComposer uriComposer,
            SignInManager<ApplicationUser> signInManager,
            IAppLogger<BasketController> logger)
        {
            _basketService = basketService;
            _uriComposer = uriComposer;
            _signInManager = signInManager;
            _logger = logger;
            _orderService = orderService;
            _basketViewModelService = basketViewModelService;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var basketModel = await GetBasketViewModelAsync();

            return View(basketModel);
        }

        [HttpPost]
        public async Task<IActionResult> Index(Dictionary<string, int> items)
        {
            var basketViewModel = await GetBasketViewModelAsync();
            await _basketService.SetQuantities(basketViewModel.Id, items);

            return View(await GetBasketViewModelAsync());
        }


        // POST: /Basket/AddToBasket
        [HttpPost]
        public async Task<IActionResult> AddToBasket(CatalogItemViewModel productDetails)
        {
            if (productDetails?.Id == null)
            {
                return RedirectToAction("Index", "Catalog");
            }
            var basketViewModel = await GetBasketViewModelAsync();

            await _basketService.AddItemToBasket(basketViewModel.Id, productDetails.Id, productDetails.Price, 1);

            return RedirectToAction("Index");
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Checkout(Dictionary<string, int> items)
        {
            var basketViewModel = await GetBasketViewModelAsync();
            await _basketService.SetQuantities(basketViewModel.Id, items);

            await _orderService.CreateOrderAsync(basketViewModel.Id, new Address("123 Main St.", "Kent", "OH", "United States", "44240"));

            await _basketService.DeleteBasketAsync(basketViewModel.Id);

            return View("Checkout");
        }

        private async Task<BasketViewModel> GetBasketViewModelAsync()
        {
            if (_signInManager.IsSignedIn(HttpContext.User))
            {
                return await _basketViewModelService.GetOrCreateBasketForUser(User.Identity.Name);
            }
            string anonymousId = GetOrSetBasketCookie();
            return await _basketViewModelService.GetOrCreateBasketForUser(anonymousId);
        }

        private string GetOrSetBasketCookie()
        {
            if (Request.Cookies.ContainsKey(Constants.BASKET_COOKIENAME))
            {
                return Request.Cookies[Constants.BASKET_COOKIENAME];
            }
            string anonymousId = Guid.NewGuid().ToString();
            var cookieOptions = new CookieOptions();
            cookieOptions.Expires = DateTime.Today.AddYears(10);
            Response.Cookies.Append(Constants.BASKET_COOKIENAME, anonymousId, cookieOptions);
            return anonymousId;
        }
    }
}

src/Web/Controllers/CatalogController.cs
using Microsoft.eShopWeb.Web.Services;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace Microsoft.eShopWeb.Web.Controllers
{
    [Route("")]
    public class CatalogController : Controller
    {
        private readonly ICatalogService _catalogService;

        public CatalogController(ICatalogService catalogService) => _catalogService = catalogService;

        [HttpGet]
        [HttpPost]
        public async Task<IActionResult> Index(int? brandFilterApplied, int? typesFilterApplied, int? page)
        {
            var itemsPage = 10;           
            var catalogModel = await _catalogService.GetCatalogItems(page ?? 0, itemsPage, brandFilterApplied, typesFilterApplied);
            return View(catalogModel);
        }

        [HttpGet("Error")]
        public IActionResult Error()
        {
            return View();
        }
    }
}

src/Web/Views/Catalog/Index.cshtml
@{
    ViewData["Title"] = "Catalog";
    @model CatalogIndexViewModel
}
<section class="esh-catalog-hero">
    <div class="container">
        <img class="esh-catalog-title" src="../images/main_banner_text.png" />
    </div>
</section>

<section class="esh-catalog-filters">
    <div class="container">
        <form asp-action="Index" asp-controller="Catalog" method="post">
            <label class="esh-catalog-label" data-title="brand">
                <select asp-for="@Model.BrandFilterApplied" asp-items="@Model.Brands" class="esh-catalog-filter"></select>
            </label>
            <label class="esh-catalog-label" data-title="type">
                <select asp-for="@Model.TypesFilterApplied" asp-items="@Model.Types" class="esh-catalog-filter"></select>
            </label>
            <input class="esh-catalog-send" type="image" src="images/arrow-right.svg" />
        </form>
    </div>
</section>

<div class="container">

    @if (Model.CatalogItems.Any())
    {
        <partial name="_pagination" for="PaginationInfo" />

        <div class="esh-catalog-items row">
            @foreach (var catalogItem in Model.CatalogItems)
            {
                <div class="esh-catalog-item col-md-4">
                    <partial name="_product" model="catalogItem" />
                </div>
            }
        </div>

        <partial name="_pagination" for="PaginationInfo" />
    }
    else
    {
        <div class="esh-catalog-items row">
            THERE ARE NO RESULTS THAT MATCH YOUR SEARCH
        </div>
    }
</div>

src/Web/Views/Catalog/_pagination.cshtml
@model PaginationInfoViewModel

<div class="esh-pager">
	<div class="container-fluid">
		<article class="esh-pager-wrapper row">
			<nav>
				<div class="col-md-2 col-xs-12">
					<a class="esh-pager-item-left esh-pager-item--navigable @Model.Previous"
					   id="Previous"
					   asp-controller="Catalog"
					   asp-action="Index"
					   asp-route-page="@(Model.ActualPage - 1)"
					   aria-label="Previous">
						Previous
					</a>
				</div>
				
				<div class="col-md-8 col-xs-12">
					<span class="esh-pager-item">
						Showing @Model.ItemsPerPage of @Model.TotalItems products - Page @(Model.ActualPage + 1) - @Model.TotalPages
					</span>
				</div>
		        
				<div class="col-md-2 col-xs-12">
					<a class="esh-pager-item-right esh-pager-item--navigable @Model.Next"
					   id="Next"
					   asp-controller="Catalog"
					   asp-action="Index"
					   asp-route-page="@(Model.ActualPage + 1)"
					   aria-label="Next">
						Next
					</a>
				</div>
			</nav>
		</article>
	</div>
</div>

src/Web/Views/Catalog/_product.cshtml
@model CatalogItemViewModel


<form asp-controller="Basket" asp-action="AddToBasket">

    <img class="esh-catalog-thumbnail" src="@Model.PictureUri" />
    <input class="esh-catalog-button" type="submit" value="[ ADD TO BASKET ]" />

    <div class="esh-catalog-name">
        <span>@Model.Name</span>
    </div>
    <div class="esh-catalog-price">
        <span>@Model.Price.ToString("N2")</span>
    </div>
    @*<input type="hidden" asp-for="@Model.CatalogBrand" name="brand" />
    <input type="hidden" asp-for="@Model.CatalogBrandId" name="brandId" />
    <input type="hidden" asp-for="@Model.CatalogType" name="type" />
    <input type="hidden" asp-for="@Model.CatalogTypeId" name="typeId" />
    <input type="hidden" asp-for="@Model.Description" name="description" />*@
    <input type="hidden" asp-for="@Model.Id" name="id" />
    <input type="hidden" asp-for="@Model.Name" name="name" />
    <input type="hidden" asp-for="@Model.PictureUri" name="pictureUri" />
    <input type="hidden" asp-for="@Model.Price" name="price" />
</form>